name: Gradle Dependency Submission
on:
  push:
    branches:
      - development # Run the action on the develop branch or your default branch

jobs:
  build:
    name: Dependencies
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
    
      - name: 'Checkout Repository'
        uses: actions/checkout@v4 
        
      - name: Grant executable permissions to gradlew
        run: chmod +x gradlew

      - name: Setup Gradle to generate and submit dependency graphs
        uses: gradle/gradle-build-action@v2
        with:
           dependency-graph: generate-and-submit
           
      - name: Run a build and generate the dependency graph which will be submitted post-job
        run: ./gradlew build
